name: Bug Report
description: Report a reproducible bug in Zipline
title: 'Bug: [short description of the issue]'
labels: ['bug']
body:
  - type: textarea
    id: what-happened
    attributes:
      label: Bug description
      description: |
        Describe in detail what you were doing and what happened.
        Please include screenshots, logs, or error messages if possible, as they help diagnose the issue faster.
    validations:
      required: true

  - type: dropdown
    id: runtime-type
    attributes:
      label: How is Zipline being run?
      description:
      options:
        - On docker (docker, docker compose, etc.)
        - Built from source (running it through `pnpm start` or `node`, etc.)
        - Other (please specify in the "Zipline Version" section)
    validations:
      required: true

  - type: textarea
    id: runtime-version
    attributes:
      label: Zipline Version
      description: |
        Provide the version of Zipline you are using:
        - If version checking is enabled (it is by default): paste the response from `http://<domain>/api/version`
        - If using docker (and can't do the above): specify the tag you are using (`latest`, `trunk`, or a tag digest)
        - A simple version number (e.g. "4.2.1") may also suffice
      placeholder: '4.2.1'
    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: If applicable, what browsers are you seeing this issue on?
      multiple: true
      options:
        - Chromium based (Chrome, Brave, Edge, Opera, etc.)
        - Firefox based (Firefox, Zen Browser, Waterfox, etc.)
        - Safari (On macOS and/or iOS)
        - Chromium based on Android/iOS
        - Firefox based on Android/iOS
        - Other (Please specify in the "Steps to Reproduce" section)

  - type: textarea
    id: zipline-logs
    attributes:
      label: Relevant Logs
      description: |
        Paste any relevant logs from Zipline or the browser (if applicable).
        If logs don't look useful, you can enable debug mode by setting the environment variable `DEBUG=zipline` when starting Zipline.
        Then reproduce the issue and copy the logs here.
        **Note:** Debug logs may contain sensitive information.

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: |
        Please list the exact steps required to reproduce the issue.
        Include any relevant configuration options, settings, or external services that may affect Zipline’s functionality.
